Repository SymmetricDevs/Susy-Core, pull requests merged in 2025-07, with the labels that each got.

#477 Moon dimension
  src/main/java/supersymmetry/api/blocks/VariantBlockFalling.java
  src/main/java/supersymmetry/api/blocks/VariantItemBlockFalling.java
  src/main/java/supersymmetry/api/unification/ore/SusyOrePrefix.java
  src/main/java/supersymmetry/api/unification/ore/SusyStoneTypes.java
  src/main/java/supersymmetry/client/renderer/sky/SkyRendererMoon.java
  src/main/java/supersymmetry/common/CommonProxy.java
  src/main/java/supersymmetry/common/EventHandlers.java
  src/main/java/supersymmetry/common/blocks/BlockDeposit.java
  src/main/java/supersymmetry/common/blocks/BlockRegolith.java
  src/main/java/supersymmetry/common/blocks/SuSyBlocks.java
  src/main/java/supersymmetry/common/blocks/SusyStoneVariantBlock.java
  src/main/java/supersymmetry/common/event/GravityHandler.java
  src/main/java/supersymmetry/common/materials/SuSySecondDegreeMaterials.java
  src/main/java/supersymmetry/common/materials/SusyMaterials.java
  src/main/java/supersymmetry/common/world/Planet.java
  src/main/java/supersymmetry/common/world/PlanetBiomeProvider.java
  src/main/java/supersymmetry/common/world/PlanetChunkGenerator.java
  src/main/java/supersymmetry/common/world/SuSyBiomes.java
  src/main/java/supersymmetry/common/world/SuSyDimensions.java
  src/main/java/supersymmetry/common/world/WorldProviderPlanet.java
  src/main/java/supersymmetry/common/world/biome/BiomeLunarHighlands.java
  src/main/java/supersymmetry/common/world/biome/BiomeLunarMaria.java
  src/main/java/supersymmetry/common/world/biome/PlanetaryBiome.java
  src/main/java/supersymmetry/common/world/layer/PlanetGenLayerBiomes.java
  src/main/java/supersymmetry/loaders/recipes/SusyOreRecipeHandler.java
  src/main/java/supersymmetry/mixins/minecraft/BlockFireMixin.java
  src/main/java/supersymmetry/mixins/minecraft/EntityFallingBlockMixin.java
  src/main/java/supersymmetry/mixins/minecraft/EntityMinecartMixin.java
  src/main/java/supersymmetry/mixins/minecraft/EntityMixin.java
  src/main/java/supersymmetry/mixins/minecraft/EntityPlayerMixin.java
  src/main/java/supersymmetry/mixins/minecraft/EntityTNTPrimedMixin.java
  src/main/java/supersymmetry/modules/SuSyCoreModule.java
  src/main/resources/assets/gregtech/textures/blocks/susy_stones/anorthosite.png
  src/main/resources/assets/gregtech/textures/blocks/susy_stones/anorthosite_bricks.png
  src/main/resources/assets/gregtech/textures/blocks/susy_stones/anorthosite_cobble.png
  src/main/resources/assets/gregtech/textures/blocks/susy_stones/regolith/highland.png
  src/main/resources/assets/gregtech/textures/blocks/susy_stones/regolith/lowland.png
  src/main/resources/assets/gregtech/textures/earth-icon.png
  src/main/resources/assets/gregtech/textures/moon-icon.png
  src/main/resources/assets/susy/blockstates/deposit_block.json
  src/main/resources/assets/susy/blockstates/regolith.json
  src/main/resources/assets/susy/blockstates/susy_stone_bricks.json
  src/main/resources/assets/susy/blockstates/susy_stone_cobble.json
  src/main/resources/assets/susy/blockstates/susy_stone_smooth.json
  src/main/resources/assets/susy/lang/en_us.lang
  src/main/resources/assets/susy/textures/environment/earth_phases.png
  src/main/resources/mixins.susy.early.json
Labels: internal

#478 Separate Pyrotech contents into its own module
  dependencies.gradle
  src/main/java/supersymmetry/common/EventHandlers.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/integration/bdsandm/BDSAndMModule.java
  src/main/java/supersymmetry/integration/pyrotech/PyrotechModule.java
  src/main/java/supersymmetry/modules/SuSyModules.java
Labels: internal

#475 Pipenet walker (now returned from death)
  src/api/java/mods/railcraft/api/items/IToolCrowbar.java
  src/api/java/mrtjp/projectred/api/IScrewdriver.java
  src/main/java/supersymmetry/client/ClientProxy.java
  src/main/java/supersymmetry/common/item/ToolBehaviorExtender.java
  src/main/java/supersymmetry/common/item/behavior/PipeNetWalkerBehavior.java
  src/main/java/supersymmetry/common/item/behavior/PipeOperationWalker.java
  src/main/java/supersymmetry/common/item/behavior/TraverseOption.java
  src/main/java/supersymmetry/mixins/gregtech/BlockPipeAccessor.java
  src/main/java/supersymmetry/mixins/gregtech/ToolBuilderAccessor.java
  src/main/java/supersymmetry/mixins/gregtech/ToolItemsMixin.java
  src/main/resources/assets/susy/lang/en_us.lang
  src/main/resources/mixins.susy.gregtech.json
Labels: feature

#455 Add mixer settler multiblock
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/api/recipes/builders/MixerSettlerRecipeBuilder.java
  src/main/java/supersymmetry/api/recipes/properties/MixerSettlerCellsProperty.java
  src/main/java/supersymmetry/common/blocks/BlockSuSyMultiblockCasing.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityMixerSettler.java
  src/main/java/supersymmetry/loaders/recipes/CoagulationRecipes.java
  src/main/resources/assets/gregtech/textures/blocks/multiblock_casing/coalescence_plate.png
  src/main/resources/assets/susy/blockstates/susy_multiblock_casing.json
  src/main/resources/assets/susy/lang/en_us.lang
Labels: feature

#485 fix: reverberatory furnace not using primitive hatches
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityReverberatoryFurnace.java
  src/main/java/supersymmetry/common/metatileentities/multiblockpart/MetaTileEntityPrimitiveItemBus.java
Labels: fix

#486 Fix Lost Translation Keys
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityArcFurnaceComplex.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityMetallurgicalConverter.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/strand/MetaTileEntityStrandShaper.java
  src/main/java/supersymmetry/common/metatileentities/single/electric/MetaTileEntityIncinerator.java
  src/main/resources/assets/susy/lang/en_us.lang
Labels: fix

#487 Hotfixes
  dependencies.gradle
  src/main/java/supersymmetry/api/metatileentity/IMui2MetaTileEntity.java
  src/main/java/supersymmetry/api/stockinteraction/StockFilter.java
  src/main/java/supersymmetry/common/item/ToolBehaviorExtender.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/single/railinterfaces/MetaTileEntityLocomotiveController.java
  src/main/java/supersymmetry/common/metatileentities/single/railinterfaces/MetaTileEntityStockInteractor.java
  src/main/java/supersymmetry/integration/pyrotech/PyrotechModule.java
  src/main/java/supersymmetry/integration/theoneprobe/provider/StrandShaperInfoProvider.java
  src/main/java/supersymmetry/mixins/gregtech/AnonToolDefinitionAccessor.java
  src/main/java/supersymmetry/mixins/gregtech/ToolBuilderAccessor.java
  src/main/java/supersymmetry/mixins/gregtech/ToolItemsMixin.java
  src/main/java/supersymmetry/mixins/reccomplex/RCPosTransformerMixin.java
  src/main/resources/assets/susy/lang/en_us.lang
  src/main/resources/mixins.susy.gregtech.json
Labels: internal

#489 Fix Fluidlogged API mixin
  .gitignore
  dependencies.gradle
  libs/AppleCore-mc1.12.2-3.4.0.jar
  libs/GregicalityMultiblocks-1.12.2-1.2.1-sources.jar
  libs/gregtechfoodoption-1.9.3.jar
  src/main/java/supersymmetry/asm/SusyLoadingPlugin.java
  src/main/java/supersymmetry/mixins/fluidlogged_api/BlockFluidBaseHookMixin.java
  src/main/java/supersymmetry/mixins/gregtech/TargetBlockAccessMixin.java
  src/main/resources/mixins.susy.fluidlogged_api.early.json
  src/main/resources/mixins.susy.gregtech.json
Labels: fix

#493 rick asked for this
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
Labels: internal

#495 fix: removes lwjgl
  src/main/java/supersymmetry/api/stockinteraction/StockHelperFunctions.java
Labels: fix

#492 Update MetaTileEntityArcFurnaceComplex.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityArcFurnaceComplex.java
Labels: fix

#491 Chinese Translation Fix
  src/main/resources/assets/susy/lang/zh_cn.lang
Labels: fix

#500 Make poly tank use dedicated texture
  src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityPolymerizationTank.java
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front_paused.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/polymerization_tank/overlay_front_paused_emissive.png
Labels: internal

#501 Finalization
  src/main/java/supersymmetry/api/unification/material/info/SuSyMaterialFlags.java
  src/main/java/supersymmetry/api/unification/material/info/SuSyMaterialIconSets.java
  src/main/java/supersymmetry/api/unification/material/info/SuSyMaterialIconType.java
  src/main/java/supersymmetry/api/unification/material/properties/SuSyPropertyKey.java
  src/main/java/supersymmetry/api/unification/ore/SusyOrePrefix.java
Labels: internal

#499 Fix some GT lamps not rendering in the inventory when both VintageFix & CTM are installed
  dependencies.gradle
  src/main/java/supersymmetry/integration/vintagefix/VintageFixModule.java
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/mixins/vintagefix/LampBakedModelAccessor.java
  src/main/java/supersymmetry/mixins/vintagefix/LampBakedModelMixin.java
  src/main/java/supersymmetry/modules/SuSyModules.java
  src/main/resources/mixins.susy.vintagefix.json
Labels: fix

#498 You cannot harvest deposits with anything
  src/main/java/supersymmetry/common/blocks/BlockDeposit.java
  src/main/resources/assets/susy/lang/en_us.lang
  src/main/resources/assets/susy/lang/ru_RU.lang
  src/main/resources/assets/susy/lang/zh_cn.lang
Labels: internal

#483 Injection Molder
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityInjectionMolder.java
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/injection_molder/overlay_front.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/injection_molder/overlay_front_active.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/injection_molder/overlay_front_active_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/injection_molder/overlay_front_emissive.png
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/injection_molder/overlay_front_paused.png
  src/main/resources/assets/susy/lang/en_us.lang
Labels: feature

#504 updated code breacher crate overlay texture
  src/main/resources/assets/susy/textures/blocks/code_breacher_crate.png
Labels: internal

#508 Fix wrong translation key in injection molder
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityInjectionMolder.java
Labels: fix

#490 Update buildscript
  .gitignore
  build.gradle
  buildscript.properties
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: internal

#510 The great LT loot overhaul
  dependencies.gradle
  src/main/java/supersymmetry/common/metatileentities/storage/MetaTileEntityLockedCrate.java
  src/main/java/supersymmetry/integration/littletiles/LittleTilesModule.java
  src/main/java/supersymmetry/modules/SuSyModules.java
Labels: feature

#512 Fix rft crashing for pipe inv
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/mixins/gregtech/TileEntityPipeBaseMixin.java
  src/main/java/supersymmetry/mixins/mcjtylib/InventoryHelperMixin.java
Labels: fix
