Repository SymmetricDevs/Susy-Core, pull requests merged in 2025-06, with the labels that each got.

#445 bump fluid outputs for rotary kiln
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
Labels: change

#444 fix #332
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityDumper.java
Labels: fix

#448 Disable elytra boost
  src/main/java/supersymmetry/mixins/minecraft/EntityElytraMixin.java
  src/main/resources/mixins.susy.early.json
Labels: change

#452 Teach JEI to distinguish IR rolling stock variants
  src/main/java/supersymmetry/integration/jei/JeiModule.java
  src/main/java/supersymmetry/integration/jei/RollingStockSubtypeHandler.java
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/modules/SuSyModules.java
  src/main/resources/mixins.susy.immersiverailroading.json
Labels: fix

#458 Remove yungs mixin & cleanup gt pipetile mixin
  dependencies.gradle
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/mixins/gregtech/TileEntityPipeBaseMixin.java
  src/main/java/supersymmetry/mixins/yungs/MixinSideRoom.java
  src/main/java/supersymmetry/mixins/yungs/MixinZombieVillagerRoom.java
  src/main/resources/mixins.susy.yungs.json
Labels: internal

#463 feat: small flavor text
  src/main/java/supersymmetry/client/ClientProxy.java
  src/main/java/supersymmetry/common/EventHandlers.java
  src/main/resources/assets/susy/lang/en_us.lang
Labels: internal

#462 Quarry
  src/main/java/supersymmetry/api/capability/impl/QuarryLogic.java
  src/main/java/supersymmetry/api/gui/SusyGuiTextures.java
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/api/recipes/builders/DimensionRecipeBuilder.java
  src/main/java/supersymmetry/api/recipes/properties/DimensionProperty.java
  src/main/java/supersymmetry/api/recycling/ItemLikeRecyclable.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityDronePad.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityQuarry.java
  src/main/java/supersymmetry/loaders/recipes/handlers/RecyclingManager.java
  src/main/resources/assets/gregtech/textures/gui/widget/button_quarry_modes.png
  src/main/resources/assets/susy/lang/en_us.lang
Labels: feature

#467 Fix base texture for molds
  src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/strand/MetaTileEntityBilletMold.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/strand/MetaTileEntitySlabMold.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/strand/MetaTileEntityStrandMold.java
  src/main/resources/assets/gregtech/textures/blocks/machines/multiblocks/natural_draft_cooling_tower/overlay_front_active.png
Labels: fix

#425 Fix SUSY Stone -> Gravel/SUSY Cobble recipe conflict
  src/main/java/supersymmetry/loaders/SusyOreDictionaryLoader.java
  src/main/java/supersymmetry/loaders/recipes/SuSyRecipeLoader.java
Labels: fix
