Repository SymmetricDevs/Susy-Core, pull requests merged in 2025-04, with the labels that each got.

#408 Rocket
  src/main/java/supersymmetry/SuSyValues.java
  src/main/java/supersymmetry/Supersymmetry.java
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/api/sound/SusySounds.java
  src/main/java/supersymmetry/client/ClientProxy.java
  src/main/java/supersymmetry/client/audio/MovingSoundRocket.java
  src/main/java/supersymmetry/client/renderer/handler/RocketModel.java
  src/main/java/supersymmetry/client/renderer/handler/RocketRenderer.java
  src/main/java/supersymmetry/client/renderer/particles/SusyParticleFlameLarge.java
  src/main/java/supersymmetry/client/renderer/particles/SusyParticleSmokeLarge.java
  src/main/java/supersymmetry/common/CommonProxy.java
  src/main/java/supersymmetry/common/SusyMetaEntities.java
  src/main/java/supersymmetry/common/blocks/BlockRocketAssemblerCasing.java
  src/main/java/supersymmetry/common/blocks/BlockSuSyMultiblockCasing.java
  src/main/java/supersymmetry/common/blocks/SuSyBlocks.java
  src/main/java/supersymmetry/common/entities/EntityRocket.java
  src/main/java/supersymmetry/common/item/SuSyMetaItems.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/MetaTileEntityLandingPad.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityLaunchPad.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityRocketAssembler.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityRocketProgrammer.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityScrapRecycler.java
  src/main/resources/assets/gregtech/models/item/metaitems/orbital.scrap.earth.json
  src/main/resources/assets/gregtech/textures/blocks/multiblock_casing/heavy_duty_pad.png
  src/main/resources/assets/gregtech/textures/blocks/multiblock_casing/heavy_duty_pad.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/multiblock_casing/heavy_duty_pad_ctm.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/foundation.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/rails.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/rails.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/rails_ctm.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/reinforced_foundation.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/reinforced_foundation.png.mcmeta
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/reinforced_foundation_ctm.png
  src/main/resources/assets/gregtech/textures/blocks/rocket_assembler_casing/structural_frame.png
  src/main/resources/assets/gregtech/textures/items/metaitems/orbital.scrap.earth.png
  src/main/resources/assets/susy/blockstates/rocket_assembler_casing.json
  src/main/resources/assets/susy/blockstates/susy_multiblock_casing.json
  src/main/resources/assets/susy/lang/en_us.lang
  src/main/resources/assets/susy/models/entity/soyuz.mtl
  src/main/resources/assets/susy/models/entity/soyuz.obj
  src/main/resources/assets/susy/sounds.json
  src/main/resources/assets/susy/sounds/rocket_launch.ogg
  src/main/resources/assets/susy/textures/entities/rocket.png
  src/main/resources/assets/susy/textures/entities/soyuz.png
Labels: feature

#414 minor fixes
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityVacuumDistillationTower.java
Labels: fix

#417 water and lava now have voidable with dumper tooltip
  src/main/java/supersymmetry/loaders/SuSyFluidTooltipLoader.java
Labels: change

#418 fix condenser consuming energy
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityCondenser.java
Labels: fix

#421 gradle update?
  build.gradle
  settings.gradle
Labels: internal

#422 rebalance input/output slots
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/common/CommonProxy.java
  src/main/java/supersymmetry/mixins/gregtech/MetaTileEntityFluidDrillMixin.java
  src/main/java/supersymmetry/mixins/gregtech/MetaTileEntityLargeMinerMixin.java
  src/main/java/supersymmetry/mixins/gregtech/MetaTileEntityMinerMixin.java
  src/main/resources/mixins.susy.gregtech.json
Labels: internal
