Repository SymmetricDevs/Susy-Core, pull requests merged in 2025-08, with the labels that each got.

#514 Ol rc UUID fix
  src/main/java/supersymmetry/mixins/reccomplex/GenericStructureMixin.java
  src/main/resources/mixins.susy.reccomplex.json
Labels: fix

#516 more slots for tube furnace
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
Labels: change

#517 the great unfucking of UUID mixin
  dependencies.gradle
  src/main/java/supersymmetry/mixins/reccomplex/GenericStructureMixin.java
  src/main/java/supersymmetry/mixins/reccomplex/RCAccessorEntityMixin.java
  src/main/resources/mixins.susy.reccomplex.json
Labels: fix

#521 Added Fake wool
  src/main/java/supersymmetry/common/CommonProxy.java
  src/main/java/supersymmetry/common/blocks/BlocksFakeWool.java
  src/main/java/supersymmetry/common/blocks/SuSyBlocks.java
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_black.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_blue.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_brown.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_cyan.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_gray.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_green.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_light_blue.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_lime.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_magenta.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_orange.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_pink.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_purple.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_red.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_silver.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_white.png
  src/main/resources/assets/gregtech/textures/blocks/wool/wool_colored_yellow.png
  src/main/resources/assets/susy/blockstates/fake_wool.json
  src/main/resources/assets/susy/lang/en_us.lang
Labels: feature

#515 Boiler rework
  src/main/java/supersymmetry/api/capability/impl/SuSyBoilerLogic.java
  src/main/java/supersymmetry/api/recipes/SuSyRecipeMaps.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/steam/MetaTileEntitySuSyLargeBoiler.java
  src/main/java/supersymmetry/common/metatileentities/multi/steam/SuSyBoilerType.java
  src/main/java/supersymmetry/common/metatileentities/single/steam/SuSyCoalBoiler.java
  src/main/java/supersymmetry/common/metatileentities/single/steam/SuSyLiquidBoiler.java
  src/main/java/supersymmetry/integration/jei/JeiModule.java
  src/main/resources/assets/susy/lang/en_us.lang
Labels: change

#520 SussyPatches integration
  .gitignore
  dependencies.gradle
  run/config/sussypatches.cfg
  src/main/java/supersymmetry/Supersymmetry.java
  src/main/java/supersymmetry/api/metatileentity/MetaTileEntityGuiFactory.java
  src/main/java/supersymmetry/api/metatileentity/Mui2Utils.java
  src/main/java/supersymmetry/api/stockinteraction/StockFilter.java
  src/main/java/supersymmetry/client/ClientProxy.java
  src/main/java/supersymmetry/client/renderer/textures/SuSyConnectedTextures.java
  src/main/java/supersymmetry/client/renderer/textures/SusyTextures.java
  src/main/java/supersymmetry/common/CommonProxy.java
  src/main/java/supersymmetry/common/metatileentities/SuSyMetaTileEntities.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityHighPressureLargeTurbine.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityMultiStageFlashDistiller.java
  src/main/java/supersymmetry/common/metatileentities/single/railinterfaces/MetaTileEntityLocomotiveController.java
  src/main/java/supersymmetry/common/metatileentities/single/railinterfaces/MetaTileEntityStockInteractor.java
  src/main/java/supersymmetry/integration/vintagefix/VintageFixModule.java
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/mixins/gregtech/BlockMachineMixin.java
  src/main/java/supersymmetry/mixins/gregtech/CommonProxyMixin.java
  src/main/java/supersymmetry/mixins/gregtech/MetaTileEntityMixin.java
  src/main/java/supersymmetry/mixins/gregtech/SyncedTileEntityBaseMixin.java
  src/main/java/supersymmetry/mixins/gregtech/TargetBlockAccessMixin.java
  src/main/java/supersymmetry/mixins/gregtech/TileEntityPipeBaseMixin.java
  src/main/java/supersymmetry/mixins/vintagefix/LampBakedModelAccessor.java
  src/main/java/supersymmetry/mixins/vintagefix/LampBakedModelMixin.java
  src/main/java/supersymmetry/modules/SuSyModules.java
  src/main/resources/mixins.susy.gregtech.json
  src/main/resources/mixins.susy.mcjtylib_ng.json
  src/main/resources/mixins.susy.vintagefix.json
Labels: internal

#527 Implemented flexible dimensions for the Quarry from 15x15 to 31x31
  src/main/java/supersymmetry/api/capability/impl/QuarryLogic.java
  src/main/java/supersymmetry/api/util/Grid3D.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityQuarry.java
  src/main/resources/assets/susy/lang/en_us.lang
Labels: feature

#538 Update to mui-rc6
  dependencies.gradle
  src/main/java/supersymmetry/api/metatileentity/Mui2Utils.java
Labels: internal

#540 Fixes LT crash when a model is exploded
  src/main/java/supersymmetry/mixins/SuSyLateMixinLoader.java
  src/main/java/supersymmetry/mixins/littletiles/StructureTileList_GetTileEntity_GuardMixin.java
  src/main/resources/mixins.susy.littletiles.json
Labels: fix

#542 Disallow entities spawning on metallurgy blocks
  src/main/java/supersymmetry/common/blocks/BlockMetallurgy.java
  src/main/java/supersymmetry/common/blocks/BlockMetallurgy2.java
  src/main/java/supersymmetry/common/blocks/BlockMetallurgyRoll.java
  src/main/java/supersymmetry/common/metatileentities/multi/electric/MetaTileEntityEvaporationPool.java
Labels: fix
